package com.example.Mini_Bookstore.entity;


public enum Category {
    ART_MUSIC, BIOGRAPHIES, BUSINESS, COMICS, COMPUTERS_TECH, COOKING, HEALTH_FITNESS, HISTORY,
    HOBBIES_CRAFTS, HOME_GARDEN, HORROR, KIDS, MEDICAL, MYSTERIOUS, RELIGION, ROMANCE, FANTASY,
    SCIENCE, SELF_HELP, SOCIAL_SCIENCE, SPORTS, TEEN, TRAVEL, TRUE_CRIME, WESTERNS
}
